<a href="https://colab.research.google.com/github/yshzjq/Step-1.-Python-SQL-/blob/main/%EC%B1%95%ED%84%B03_Pandas_Matplotlib%C2%B7Seaborn/3_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd
df = pd.read_csv('seoul-rainfall-data.csv', encoding='cp949')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   날짜       366 non-null    object
 1   지점       366 non-null    int64
 2   강수량(mm)  160 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 8.7+ KB

In [45]:
df.isnull()

        날짜     지점  강수량(mm)
0    False  False    False
1    False  False    False
2    False  False    False
3    False  False     True
4    False  False    False
..     ...    ...      ...
361  False  False    False
362  False  False     True
363  False  False     True
364  False  False    False
365  False  False    False

[366 rows x 3 columns]

In [46]:
df.isnull().sum()

날짜           0
지점           0
강수량(mm)    206
dtype: int64

In [47]:
print((df['강수량(mm)'].isnull().sum())/len(df) * 100)
#강수량의 결측치 비율

56.284153005464475

In [48]:
print(f"원본 행 수 : {len(df)}")

df_cleaned = df.dropna()
print(f"삭제 후 행 수 : {len(df_cleaned)}")

원본 행 수 : 366
삭제 후 행 수 : 160

In [49]:
import pandas as pd
df = pd.read_csv('seoul-rainfall-data.csv', encoding='cp949')

print(df['강수량(mm)'].isnull().sum())
df['강수량(mm)'].fillna(0)
print(df['강수량(mm)'].isnull().sum())

df['정제된 데이터'] = df['강수량(mm)'].fillna(0)
print(df['정제된 데이터'].isnull().sum())

206
206
0

In [50]:
df['정제된 데이터'] = df['강수량(mm)'].fillna('Unknown')
print(df['정제된 데이터'].isnull().sum())

0

In [51]:
print(df['강수량(mm)'].sum()) # 총합
print(df['강수량(mm)'].isnull()) # 결측치 여부 확인
print(df['강수량(mm)'].isnull().sum()) # 결측치 몇개인지 True가 결측치

1311.4
0      False
1      False
2      False
3       True
4      False
       ...
361    False
362     True
363     True
364    False
365    False
Name: 강수량(mm), Length: 366, dtype: bool
206

In [52]:
df.isnull().sum()

날짜           0
지점           0
강수량(mm)    206
정제된 데이터      0
dtype: int64

In [53]:
missing_count = df['강수량(mm)'].isnull().sum()
total_count = len(df)
missing_ratio = missing_count / total_count * 100
print(f"결측치 비율 : {missing_ratio:.2f}%")

결측치 비율 : 56.28%

In [54]:
df.dropna()

             날짜   지점  강수량(mm) 정제된 데이터
0    2024-01-01  108      0.0     0.0
1    2024-01-02  108      0.0     0.0
2    2024-01-03  108      0.6     0.6
4    2024-01-05  108      0.0     0.0
5    2024-01-06  108      2.4     2.4
..          ...  ...      ...     ...
359  2024-12-25  108      0.1     0.1
360  2024-12-26  108      0.0     0.0
361  2024-12-27  108      0.0     0.0
364  2024-12-30  108      0.0     0.0
365  2024-12-31  108      0.0     0.0

[160 rows x 4 columns]

In [55]:
print(len(df))
df_cleaned = df.dropna() # 결측치 존재할 경우 다 삭제
print(len(df_cleaned)) #

df_cleaned = df.dropna(how='all')
print(len(df_cleaned)) #

df_cleaned = df.dropna(subset=['강수량(mm)'])
print(len(df_cleaned)) #

366
160
366
160

**장점**

구현이 간단함

결측치 패턴이 무작위일 때 효과적

분석 결과가 왜곡되지 않음


단점

데이터 솔실 발생

결측치 많으면 대부분 삭제됨

편향(bias)이 생길 수 있음

In [60]:

# 평균(mean)으로 채우기
df['강수량(mm)'].fillna(df['강수량(mm)'].mean())

# 중앙값(median)으로 채우기 - 이상치에 덜 민감
df['강수량(mm)'].fillna(df['강수량(mm)'].median())

# 최빈값(mode)으로 채우기 - 범주형 데이터에 적합
df['강수량(mm)'].fillna(df['강수량(mm)'].mode()[0])

0      0.0
1      0.0
2      0.6
3      0.0
4      0.0
      ...
361    0.0
362    0.0
363    0.0
364    0.0
365    0.0
Name: 강수량(mm), Length: 366, dtype: float64

# 이전 값으로 채우기 (Forward Fill)
df['온도'].fillna(method='ffill')

# 다음 값으로 채우기 (Backward Fill)
df['온도'].fillna(method='bfill')

# 선형 보간법 (Linear Interpolation)
df['온도'].interpolate(method='linear')

In [61]:
# 보간법 예시
import pandas as pd

data = pd.Series([1, 2, None, None, 5])
print("원본:", data.tolist())
print("보간:", data.interpolate().tolist())

원본: [1.0, 2.0, nan, nan, 5.0]
보간: [1.0, 2.0, 3.0, 4.0, 5.0]

In [73]:
import pandas as pd
df = pd.read_csv('seoul-rainfall-data.csv', encoding='cp949')

rainy_days = df[df['강수량(mm)'] > 0]

rainy_condition = df['강수량(mm)'] > 0

print(rainy_condition)

not_rainy_days = df[~rainy_condition]

print(not_rainy_days)

0      False
1      False
2       True
3      False
4      False
       ...
361    False
362    False
363    False
364    False
365    False
Name: 강수량(mm), Length: 366, dtype: bool
             날짜   지점  강수량(mm)
0    2024-01-01  108      0.0
1    2024-01-02  108      0.0
3    2024-01-04  108      NaN
4    2024-01-05  108      0.0
6    2024-01-07  108      NaN
..          ...  ...      ...
361  2024-12-27  108      0.0
362  2024-12-28  108      NaN
363  2024-12-29  108      NaN
364  2024-12-30  108      0.0
365  2024-12-31  108      0.0

[256 rows x 3 columns]