<a href="https://colab.research.google.com/github/yshzjq/Step-1.-Python-SQL-/blob/main/%EC%B1%95%ED%84%B03_Pandas_Matplotlib%C2%B7Seaborn/3_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df = pd.read_csv('seoul-rainfall-data.csv', encoding='cp949')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   날짜       366 non-null    object
 1   지점       366 non-null    int64
 2   강수량(mm)  160 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 8.7+ KB

In [4]:
df.isnull()

        날짜     지점  강수량(mm)
0    False  False    False
1    False  False    False
2    False  False    False
3    False  False     True
4    False  False    False
..     ...    ...      ...
361  False  False    False
362  False  False     True
363  False  False     True
364  False  False    False
365  False  False    False

[366 rows x 3 columns]

In [5]:
df.isnull().sum()

날짜           0
지점           0
강수량(mm)    206
dtype: int64

In [17]:
print((df['강수량(mm)'].isnull().sum())/len(df) * 100)
#강수량의 결측치 비율

56.284153005464475

In [19]:
print(f"원본 행 수 : {len(df)}")

df_cleaned = df.dropna()
print(f"삭제 후 행 수 : {len(df_cleaned)}")

원본 행 수 : 366
삭제 후 행 수 : 160

In [30]:
import pandas as pd
df = pd.read_csv('seoul-rainfall-data.csv', encoding='cp949')

print(df['강수량(mm)'].isnull().sum())
df['강수량(mm)'].fillna(0)
print(df['강수량(mm)'].isnull().sum())

df['정제된 데이터'] = df['강수량(mm)'].fillna(0)
print(df['정제된 데이터'].isnull().sum())

206
206
0

In [34]:
df['정제된 데이터'] = df['강수량(mm)'].fillna('Unknown')
print(df['정제된 데이터'].isnull().sum())

0