<a href="https://colab.research.google.com/github/yshzjq/Step-1.-Python-SQL-/blob/main/%EC%B1%95%ED%84%B03_Pandas_Matplotlib%C2%B7Seaborn/3_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd

sales = pd.read_csv('cafe-sales-weekly.csv')

print(sales.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7001 entries, 0 to 7000
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   주       7001 non-null   object
 1   매장      7001 non-null   object
 2   카테고리    7001 non-null   object
 3   메뉴명     7001 non-null   object
 4   수량      7001 non-null   int64
 5   매출      7001 non-null   int64
dtypes: int64(2), object(4)
memory usage: 328.3+ KB
None

In [8]:
print(sales.head(15))

      주   매장 카테고리            메뉴명  수량      매출
0   W01  강남점   음료     감튀스틱 밀크쉐이크  11   60500
1   W01  강남점   음료          유자생강차  23   92000
2   W01  강남점   음료    누룽누룽 바삭 프라페  37  203500
3   W01  강남점   음료    피넛버터 초코 프라페  46  299000
4   W01  강남점   음료        제로 체리콜라  48  264000
5   W01  강남점   음료     제로 부스트 에이드  25  137500
6   W01  강남점   음료       블루베리플럼주스  56  336000
7   W01  강남점   음료         골드키위주스  66  363000
8   W01  강남점   음료     귤 톡톡 젤리스무디  39  214500
9   W01  강남점   음료  라이트 바닐라 아몬드라떼  59  295000
10  W01  강남점   음료    제로 복숭아 아이스티   9   40500
11  W01  강남점   음료           연유라떼  58  261000
12  W01  강남점   음료        골드망고스무디  46  253000
13  W01  강남점   음료     코코넛 커피 스무디  46  253000
14  W01  강남점   음료           딸기주스  39  234000

비오는 날 매출이 떨어질까? 를 확인 목표

In [9]:
sales['카테고리'].value_counts()

카테고리
음료    5738
푸드    1205
상품      58
Name: count, dtype: int64

In [18]:
rainfall = pd.read_csv('seoul-rainfall-data.csv',encoding='cp949')
sales = pd.read_csv('cafe-sales-weekly.csv')

rainfall.head(5)

           날짜   지점  강수량(mm)
0  2024-01-01  108      0.0
1  2024-01-02  108      0.0
2  2024-01-03  108      0.6
3  2024-01-04  108      NaN
4  2024-01-05  108      0.0

In [20]:
sales.head(5)

     주   매장 카테고리          메뉴명  수량      매출
0  W01  강남점   음료   감튀스틱 밀크쉐이크  11   60500
1  W01  강남점   음료        유자생강차  23   92000
2  W01  강남점   음료  누룽누룽 바삭 프라페  37  203500
3  W01  강남점   음료  피넛버터 초코 프라페  46  299000
4  W01  강남점   음료      제로 체리콜라  48  264000

In [22]:
weekly_sales_sum = sales.groupby('주')['매출'].sum()
print(weekly_sales_sum.head(10))

주
W01    36412500
W02    35886500
W03    29890000
W04    35246000
W05    30814500
W06    33513500
W07    31537000
W08    32882500
W09    37313500
W10    40033500
Name: 매출, dtype: int64

In [25]:
weekly_sales_sum = sales.groupby('카테고리')['매출'].agg(['sum', 'mean', 'count'])
print(weekly_sales_sum.head(10))

             sum           mean  count
카테고리
상품       6849000  118086.206897     58
음료    1587334500  276635.500174   5738
푸드     222918000  184994.190871   1205

In [26]:
weekly_sales_sum = sales.groupby(['매장','카테고리'])['매출'].agg(['sum', 'mean', 'count'])
print(weekly_sales_sum.head(10))

                sum           mean  count
매장  카테고리
강남점 상품      3099000  103300.000000     30
    음료    828549500  287690.798611   2880
    푸드    113862500  191365.546218    595
홍대점 상품      3750000  133928.571429     28
    음료    758785000  265495.101470   2858
    푸드    109055500  178779.508197    610

In [63]:
rainfall['날짜'] = pd.to_datetime(rainfall['날짜'])

rainfall['주'] = 'W' + rainfall['날짜'].dt.isocalendar().week.astype(str).str.zfill(2)

print(rainfall['날짜'].head(15))

print(rainfall['날짜'].dt.isocalendar().week.head(15))


print(rainfall.head(10))

0    2024-01-01
1    2024-01-02
2    2024-01-03
3    2024-01-04
4    2024-01-05
5    2024-01-06
6    2024-01-07
7    2024-01-08
8    2024-01-09
9    2024-01-10
10   2024-01-11
11   2024-01-12
12   2024-01-13
13   2024-01-14
14   2024-01-15
Name: 날짜, dtype: datetime64[ns]
0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     2
8     2
9     2
10    2
11    2
12    2
13    2
14    3
Name: week, dtype: UInt32
          날짜   지점  강수량(mm)    주
0 2024-01-01  108      0.0  W01
1 2024-01-02  108      0.0  W01
2 2024-01-03  108      0.6  W01
3 2024-01-04  108      NaN  W01
4 2024-01-05  108      0.0  W01
5 2024-01-06  108      2.4  W01
6 2024-01-07  108      NaN  W01
7 2024-01-08  108      NaN  W02
8 2024-01-09  108      1.6  W02
9 2024-01-10  108      NaN  W02